name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: PHP Syntax Check
      uses: ./.github/actions/php-syntax-check
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
    - name: Rsync files to Production
      run: |
        SSH_HOST="${{ secrets.PRODUCTION_SERVER_HOST }}"
        SSH_USER="${{ secrets.PRODUCTION_SERVER_USER }}"
        WEB_DOC_ROOT="${{ secrets.PRODUCTION_WEB_DOC_ROOT }}/"
        rsync -avzc --delete --exclude='.*' \
         --exclude wp-config.php \
         --exclude wp-content/uploads/ \
         -e "ssh -o StrictHostKeyChecking=no" \
         ./dest/ "${SSH_USER}"@"${SSH_HOST}":"${WEB_DOC_ROOT}"